project:
  type: website
  resources: 
    - resume.pdf

website:
  title: "My Website"
  navbar:
    right:
      - href: me.qmd
        text: About Me
      - href: project.qmd
        text: Projects
  page-footer: 
     right: "&copy; 2024, Yechen Cao"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



execute: 
  freeze: auto