project:
  type: website

website:
  title: "My Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



